version: '3'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - rails
    restart: always

  rails:
    build: .
    entrypoint: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/opt/ty-dev
    working_dir: /opt/ty-dev
    depends_on:
      - mysql
    restart: always
    # binding.pryを使う場合はコメントアウトを外す
    tty: true
    stdin_open: true

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      DB_HOST: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d/charset.cnf:/etc/mysql/conf.d/charset.cnf
    restart: always

volumes:
  mysql_data:
